//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

ConfigService_getSystemConfigObject_args = function(args) {
  this.systemConfig = null;
  if (args) {
    if (args.systemConfig !== undefined) {
      this.systemConfig = args.systemConfig;
    }
  }
};
ConfigService_getSystemConfigObject_args.prototype = {};
ConfigService_getSystemConfigObject_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.systemConfig = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ConfigService_getSystemConfigObject_args.prototype.write = function(output) {
  output.writeStructBegin('ConfigService_getSystemConfigObject_args');
  if (this.systemConfig !== null && this.systemConfig !== undefined) {
    output.writeFieldBegin('systemConfig', Thrift.Type.STRING, 1);
    output.writeString(this.systemConfig);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ConfigService_getSystemConfigObject_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ConfigService_getSystemConfigObject_result.prototype = {};
ConfigService_getSystemConfigObject_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new SystemConfig();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ConfigService_getSystemConfigObject_result.prototype.write = function(output) {
  output.writeStructBegin('ConfigService_getSystemConfigObject_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ConfigService_getModelConfigObject_args = function(args) {
  this.modelConfig = null;
  if (args) {
    if (args.modelConfig !== undefined) {
      this.modelConfig = args.modelConfig;
    }
  }
};
ConfigService_getModelConfigObject_args.prototype = {};
ConfigService_getModelConfigObject_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.modelConfig = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ConfigService_getModelConfigObject_args.prototype.write = function(output) {
  output.writeStructBegin('ConfigService_getModelConfigObject_args');
  if (this.modelConfig !== null && this.modelConfig !== undefined) {
    output.writeFieldBegin('modelConfig', Thrift.Type.STRING, 1);
    output.writeString(this.modelConfig);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ConfigService_getModelConfigObject_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ConfigService_getModelConfigObject_result.prototype = {};
ConfigService_getModelConfigObject_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ModelConfig();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ConfigService_getModelConfigObject_result.prototype.write = function(output) {
  output.writeStructBegin('ConfigService_getModelConfigObject_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ConfigServiceClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
ConfigServiceClient.prototype = {};
ConfigServiceClient.prototype.getSystemConfigObject = function(systemConfig, callback) {
  this.send_getSystemConfigObject(systemConfig, callback); 
  if (!callback) {
    return this.recv_getSystemConfigObject();
  }
};

ConfigServiceClient.prototype.send_getSystemConfigObject = function(systemConfig, callback) {
  this.output.writeMessageBegin('getSystemConfigObject', Thrift.MessageType.CALL, this.seqid);
  var args = new ConfigService_getSystemConfigObject_args();
  args.systemConfig = systemConfig;
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_getSystemConfigObject();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

ConfigServiceClient.prototype.recv_getSystemConfigObject = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new ConfigService_getSystemConfigObject_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'getSystemConfigObject failed: unknown result';
};
ConfigServiceClient.prototype.getModelConfigObject = function(modelConfig, callback) {
  this.send_getModelConfigObject(modelConfig, callback); 
  if (!callback) {
    return this.recv_getModelConfigObject();
  }
};

ConfigServiceClient.prototype.send_getModelConfigObject = function(modelConfig, callback) {
  this.output.writeMessageBegin('getModelConfigObject', Thrift.MessageType.CALL, this.seqid);
  var args = new ConfigService_getModelConfigObject_args();
  args.modelConfig = modelConfig;
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_getModelConfigObject();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

ConfigServiceClient.prototype.recv_getModelConfigObject = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new ConfigService_getModelConfigObject_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'getModelConfigObject failed: unknown result';
};
