//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


declare class DiagramServiceClient {
  input: Thrift.TJSONProtocol;
  output: Thrift.TJSONProtocol;
  seqid: number;

  constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

  save(dia: DiagramDAO): boolean;

  save(dia: DiagramDAO, callback: Function): void;

  open(name: string): DiagramDAO;

  open(name: string, callback: Function): void;
}
